---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    api.service.kubernetes.io/path: "/services/helloservice/sayHello/"
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "fisjaxrs"
    version: "0.0.1-SNAPSHOT"
    group: "com.redhat.ocp.poc"
  name: "fisjaxrs"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "fisjaxrs"
    provider: "fabric8"
    group: "com.redhat.ocp.poc"
