---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/spring-boot.svg"
    fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=fisjaxrs&var-version=0.0.1-SNAPSHOT"
  labels:
    provider: "fabric8"
    project: "fisjaxrs"
    version: "0.0.1-SNAPSHOT"
    group: "com.redhat.ocp.poc"
  name: "fisjaxrs"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: "fisjaxrs"
      provider: "fabric8"
      group: "com.redhat.ocp.poc"
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: "img/icons/spring-boot.svg"
        fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=fisjaxrs&var-version=0.0.1-SNAPSHOT"
      labels:
        provider: "fabric8"
        project: "fisjaxrs"
        version: "0.0.1-SNAPSHOT"
        group: "com.redhat.ocp.poc"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "poc/fisjaxrs:snapshot-170712-093916-0216"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 180
        name: "spring-boot"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        - containerPort: 9779
          name: "prometheus"
          protocol: "TCP"
        - containerPort: 8778
          name: "jolokia"
          protocol: "TCP"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8081
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: "1.0"
          requests:
            cpu: "0.2"
        securityContext:
          privileged: false
